# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1040f816facd2f064d6e7ab9f1471d6a75095c97e642adec9d97ad3d3cb561cfa8003dc84698812a209092c1d3d4da8a0cda38bdf8810b6fca358453a0e73e07

test:
  secret_key_base: fb1a40d7688c7f6ac5b38861c7f25d3c28df87ba2f0b13988999e4d7bf510e6e43071dbde8fd515269153fbd0433d2dd414c7738011706eb979ef31d8ea86c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
